language: node_js
node_js:
    - "6.9.4"
before_script:
# Installing firefox browser
   - sudo apt-get sudo apt-get install firefox
   - Xvfb :99 -ac &
   - export DISPLAY=:99
   - firefox -v
script: node_modules/karma/bin/karma start karma.config.js --single-run
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
